telegram_token: "< TELEGRAM TOKEN >"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Asia/Almaty"
split_token: "|"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000
send_only: true

